# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wyu?useUnicode=true&useSSL=false&charaterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
mabatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
server:
  port: 8080

